packages:
  - "."

allowBuilds:
  '@parcel/watcher': true

minimumReleaseAgeExclude:
  - form-data@4.0.6
  - '@babel/core@7.29.1'
  - globals@17.10.0

overrides:
  brace-expansion: '^5.0.9'
  js-yaml: '^5.2.3'